// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCF8z-zxT9TUbXgazWv1tuo15RHbktsTs',
    appId: '1:391032609407:web:d9ea16d8d9ad334146fd4a',
    messagingSenderId: '391032609407',
    projectId: 'cafee-d184a',
    authDomain: 'cafee-d184a.firebaseapp.com',
    storageBucket: 'cafee-d184a.firebasestorage.app',
    measurementId: 'G-RQL7P5N6WY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI5OqD7-wCbXMmQvH4X2SpkTwne9KnwjQ',
    appId: '1:391032609407:android:d248009b55f4501146fd4a',
    messagingSenderId: '391032609407',
    projectId: 'cafee-d184a',
    storageBucket: 'cafee-d184a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8YG1GbMrBRsz6aBM9xhtRiiCvHmKBUeg',
    appId: '1:391032609407:ios:36eea9ba2a093d4e46fd4a',
    messagingSenderId: '391032609407',
    projectId: 'cafee-d184a',
    storageBucket: 'cafee-d184a.firebasestorage.app',
    iosBundleId: 'com.example.caffee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8YG1GbMrBRsz6aBM9xhtRiiCvHmKBUeg',
    appId: '1:391032609407:ios:36eea9ba2a093d4e46fd4a',
    messagingSenderId: '391032609407',
    projectId: 'cafee-d184a',
    storageBucket: 'cafee-d184a.firebasestorage.app',
    iosBundleId: 'com.example.caffee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCF8z-zxT9TUbXgazWv1tuo15RHbktsTs',
    appId: '1:391032609407:web:c247cc482922ceb046fd4a',
    messagingSenderId: '391032609407',
    projectId: 'cafee-d184a',
    authDomain: 'cafee-d184a.firebaseapp.com',
    storageBucket: 'cafee-d184a.firebasestorage.app',
    measurementId: 'G-JQTR652M6L',
  );
}
