import 'package:caffee/Feature/home/domain/Entity/product_entity.dart';
import 'package:caffee/Feature/home/domain/Entity/review_entity.dart';

List<ProductEntity> products = [
  ProductEntity(
    productId: 'p001',
    name: 'Ethiopian Coffee Beans',
    additional: '500g pack',
    details: 'Premium single-origin Ethiopian beans, roasted fresh weekly.',
    rate: 4.7,
    isFavorite: true,
    price: 120.0,
    reviewEntity: [ ReviewEntity(
      name: 'Ali Ahmed',
      date: '2025-10-20',
      description: 'Excellent coffee, very smooth taste!',
      rate: 4.8,
    ),
    ReviewEntity(
      name: 'Sara Mohamed',
      date: '2025-10-21',
      description: 'Nice aroma and great packaging.',
      rate: 4.5,
    ),ReviewEntity(
      name: 'Ali Ahmed',
      date: '2025-10-20',
      description: 'Excellent coffee, very smooth taste!',
      rate: 4.8,
    ),
    ReviewEntity(
      name: 'Sara Mohamed',
      date: '2025-10-21',
      description: 'Nice aroma and great packaging.',
      rate: 4.5,
    ),],
  ),
 ProductEntity(
    productId: 'p001',
    name: 'Ethiopian Coffee Beans',
    additional: '500g pack',
    details: 'Premium single-origin Ethiopian beans, roasted fresh weekly.',
    rate: 4.7,
    isFavorite: true,
    price: 120.0,
    reviewEntity: [ ReviewEntity(
      name: 'Ali Ahmed',
      date: '2025-10-20',
      description: 'Excellent coffee, very smooth taste!',
      rate: 4.8,
    ),
    ReviewEntity(
      name: 'Sara Mohamed',
      date: '2025-10-21',
      description: 'Nice aroma and great packaging.',
      rate: 4.5,
    ),ReviewEntity(
      name: 'Ali Ahmed',
      date: '2025-10-20',
      description: 'Excellent coffee, very smooth taste!',
      rate: 4.8,
    ),
    ReviewEntity(
      name: 'Sara Mohamed',
      date: '2025-10-21',
      description: 'Nice aroma and great packaging.',
      rate: 4.5,
    ),],
  ),
   ProductEntity(
    productId: 'p001',
    name: 'Ethiopian Coffee Beans',
    additional: '500g pack',
    details: 'Premium single-origin Ethiopian beans, roasted fresh weekly.',
    rate: 4.7,
    isFavorite: true,
    price: 120.0,
    reviewEntity: [ ReviewEntity(
      name: 'Ali Ahmed',
      date: '2025-10-20',
      description: 'Excellent coffee, very smooth taste!',
      rate: 4.8,
    ),
    ReviewEntity(
      name: 'Sara Mohamed',
      date: '2025-10-21',
      description: 'Nice aroma and great packaging.',
      rate: 4.5,
    ),ReviewEntity(
      name: 'Ali Ahmed',
      date: '2025-10-20',
      description: 'Excellent coffee, very smooth taste!',
      rate: 4.8,
    ),
    ReviewEntity(
      name: 'Sara Mohamed',
      date: '2025-10-21',
      description: 'Nice aroma and great packaging.',
      rate: 4.5,
    ),],
  ),
   ProductEntity(
    productId: 'p001',
    name: 'Ethiopian Coffee Beans',
    additional: '500g pack',
    details: 'Premium single-origin Ethiopian beans, roasted fresh weekly.',
    rate: 4.7,
    isFavorite: true,
    price: 120.0,
    reviewEntity: [ ReviewEntity(
      name: 'Ali Ahmed',
      date: '2025-10-20',
      description: 'Excellent coffee, very smooth taste!',
      rate: 4.8,
    ),
    ReviewEntity(
      name: 'Sara Mohamed',
      date: '2025-10-21',
      description: 'Nice aroma and great packaging.',
      rate: 4.5,
    ),ReviewEntity(
      name: 'Ali Ahmed',
      date: '2025-10-20',
      description: 'Excellent coffee, very smooth taste!',
      rate: 4.8,
    ),
    ReviewEntity(
      name: 'Sara Mohamed',
      date: '2025-10-21',
      description: 'Nice aroma and great packaging.',
      rate: 4.5,
    ),],
  ),
   ProductEntity(
    productId: 'p001',
    name: 'Ethiopian Coffee Beans',
    additional: '500g pack',
    details: 'Premium single-origin Ethiopian beans, roasted fresh weekly.',
    rate: 4.7,
    isFavorite: true,
    price: 120.0,
    reviewEntity: [ ReviewEntity(
      name: 'Ali Ahmed',
      date: '2025-10-20',
      description: 'Excellent coffee, very smooth taste!',
      rate: 4.8,
    ),
    ReviewEntity(
      name: 'Sara Mohamed',
      date: '2025-10-21',
      description: 'Nice aroma and great packaging.',
      rate: 4.5,
    ),ReviewEntity(
      name: 'Ali Ahmed',
      date: '2025-10-20',
      description: 'Excellent coffee, very smooth taste!',
      rate: 4.8,
    ),
    ReviewEntity(
      name: 'Sara Mohamed',
      date: '2025-10-21',
      description: 'Nice aroma and great packaging.',
      rate: 4.5,
    ),],
  ),
   ProductEntity(
    productId: 'p001',
    name: 'Ethiopian Coffee Beans',
    additional: '500g pack',
    details: 'Premium single-origin Ethiopian beans, roasted fresh weekly.',
    rate: 4.7,
    isFavorite: true,
    price: 120.0,
    reviewEntity: [ ReviewEntity(
      name: 'Ali Ahmed',
      date: '2025-10-20',
      description: 'Excellent coffee, very smooth taste!',
      rate: 4.8,
    ),
    ReviewEntity(
      name: 'Sara Mohamed',
      date: '2025-10-21',
      description: 'Nice aroma and great packaging.',
      rate: 4.5,
    ),ReviewEntity(
      name: 'Ali Ahmed',
      date: '2025-10-20',
      description: 'Excellent coffee, very smooth taste!',
      rate: 4.8,
    ),
    ReviewEntity(
      name: 'Sara Mohamed',
      date: '2025-10-21',
      description: 'Nice aroma and great packaging.',
      rate: 4.5,
    ),],
  ),
];
